### ISSUE TITLE
mod提交

### ISSUE THREAD

**Issue by ghitori** [vdjango/shszcraft#14]
[[矿石挖掘]OreExcavation-1.8.157](https://www.mcmod.cn/class/1955.html) （作为"[矿工的优势]MinersAdvantage"的替代品）
[[更好的末地]betterendforge-1.16.4-1.6.0](https://www.mcmod.cn/class/3163.html) (来源: Ling_xiangLX)
[[Mowzie的生物]mowziesmobs-1.5.19](https://www.mcmod.cn/class/984.html) (来源: Ling_xiangLX)
[[蔚蓝浩空]blue_skies-1.16.5-1.1.3](https://www.mcmod.cn/class/1563.html) (来源: Ling_xiangLX)
[[API]structure_gel-1.16.5-1.7.7](https://www.mcmod.cn/class/3033.html) ("[蔚蓝浩空]blue_skies"前置)
    [生物群系ID修复](预防未知的生物群系错乱)
[MrCrayfish [的家具]cfm-7.0.0pre22-1.16.3](https://www.mcmod.cn/class/263.html) (来源: a274)
[[茶风·纪事]TeaStory-4.1.12-Alpha-18](https://www.mcmod.cn/class/557.html)  (来源: a274)
[[装饰]Adorn-1.14.1+1.16.5-forge](https://www.mcmod.cn/class/1848.html) (来源: a274)
[[API]SilveroakOutpost-Forge-1.16.5-0.3.5-Beta](https://www.mcmod.cn/class/3203.html("[茶风·纪事]TeaStory"前置)
[[API]kotlinforforge-1.14.0-obf](https://www.mcmod.cn/class/2890.html)   ("[装饰]Adorn"前置)

**Comment by ShanshanHY** [comment]
[[矿石挖掘]OreExcavation-1.8.157](https://www.mcmod.cn/class/1955.html) （作为"[矿工的优势]MinersAdvantage"的替代品）
[[更好的末地]betterendforge-1.16.4-1.6.0](https://www.mcmod.cn/class/3163.html) (来源: Ling_xiangLX)
[[Mowzie的生物]mowziesmobs-1.5.19](https://www.mcmod.cn/class/984.html) (来源: Ling_xiangLX)
[[蔚蓝浩空]blue_skies-1.16.5-1.1.3](https://www.mcmod.cn/class/1563.html) (来源: Ling_xiangLX)
[[API]structure_gel-1.16.5-1.7.7](https://www.mcmod.cn/class/3033.html) ("[蔚蓝浩空]blue_skies"前置)
    [[生物群系ID修复]预防未知的生物群系错乱](https://www.curseforge.com/minecraft/mc-mods/biome-id-fixer)
[MrCrayfish [的家具]cfm-7.0.0pre22-1.16.3](https://www.mcmod.cn/class/263.html) (来源: a274)
[[茶风·纪事]TeaStory-4.1.12-Alpha-18](https://www.mcmod.cn/class/557.html)  (来源: a274)
[[装饰]Adorn-1.14.1+1.16.5-forge](https://www.mcmod.cn/class/1848.html) (来源: a274)
[[API]SilveroakOutpost-Forge-1.16.5-0.3.5-Beta](https://www.mcmod.cn/class/3203.html)("[茶风·纪事]TeaStory"前置)
[[API]kotlinforforge-1.14.0-obf](https://www.mcmod.cn/class/2890.html)   ("[装饰]Adorn"前置)
